<?php

//used to mass update the Yealink T48S phones on the network.

//ENTER CONFIG INFO HERE

$chrome_path = '"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"'; //yes that escaping and double quotation marks are exactly like they should be on windows.
$phone_user = 'admin';
$phone_pass = 'pass';
$config_file = 'DSS Keys.cfg';

$ips = array(
	'10.115.115.164',
	'10.115.115.163',
	'10.115.115.186',
	'10.115.115.179'
	
);


//DO NOT EDIT BELOW THIS PART (advanced users feel free to edit as you like)

include('vendor/autoload.php');
use HeadlessChromium\BrowserFactory;
use HeadlessChromium\Cookies\Cookie;

class YealinkPhone{
	
	private $ch,$jsessid,$phoneip,$maxlength_var;
	public $success;
	
	function __construct($phoneip,$user,$pass){
		$this->phoneip = $phoneip;
		$this->success = true;
		try {
			$browserFactory = new BrowserFactory($chrome_path);
			// starts headless chrome
			$browser = $browserFactory->createBrowser([
											'debugLogger' => 'php://stdout',
											'sendSyncDefaultTimeout' => 50000,
											'headless'=> true,         // disable headless mode
											'connectionDelay' => 0.3,   ]);
			// creates a new page and navigate to an url
			$page = $browser->createPage();
			$page->navigate("http://$phoneip")->waitForNavigation();
			
			
			
			// evaluate script in the browser
			$evaluation = $page->evaluate("document.getElementById('idUsername').value = '$user';
											document.getElementById('idPassword').value = '$pass';
											document.getElementById('idConfirm').click();")->waitForPageReload();
			
			$this->jsessid = $page->getCookies()->findOneBy('name', 'JSESSIONID');
			
			echo "\r\n\r\n\r\n The JSESSID is : ".$this->jsessid['value']."\r\n\r\n";
			
			
			//now lets open that page where you cna upload files
			$url = 'http://'.$this->phoneip.'/servlet?m=mod_data&p=settings-config&q=load';
			$page->navigate($url)->waitForNavigation();
			
			
			
			$this->maxlength_var = $page->evaluate("YLForm.RSAEncrypt('5MB');")->getReturnValue();
			
			// bye
			$browser->close();
			
		} catch (Exception $e){
			echo "\r\n\r\noh heck that didnt work - Exception was ".$e->getMessage()."\r\n\r\n";
			$this->success = false;
		}
	}
	
	
	
	function setConfigCFG($configcfg){
		//lets upload the config file
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/ - i copied the curl command from the web console of firefox and paste it here to get the php commands
		$ch = curl_init();
		
		$file = array(
			'UploadName' => new CurlFile($configcfg)
		);
		
				
		curl_setopt($ch, CURLOPT_URL, 'http://'.$this->phoneip.'/servlet?m=mod_res&p=upload&type=localcfg&maxlength='.$this->maxlength_var);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_POSTFIELDS,$file);
		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
		curl_setopt($ch, CURLOPT_SAFE_UPLOAD, 1);
		curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');
		
		$headers = array();
		$headers[] = 'Pragma: no-cache';
		$headers[] = 'Origin: http://'.$this->phoneip;
		$headers[] = 'Accept-Encoding: gzip, deflate';
		$headers[] = 'Accept-Language: en-US,en;q=0.9';
		$headers[] = 'Content-Type: multipart/form-data';
		$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36';
		$headers[] = 'Accept: */*';
		$headers[] = 'Cache-Control: no-cache';
		$headers[] = 'Referer: http://'.$this->phoneip.'/servlet?m=mod_data&p=settings-config&q=load';
		$headers[] = 'Cookie: JSESSIONID='.$this->jsessid['value'];
		$headers[] = 'Connection: keep-alive';
		$headers[] = 'Expect: ';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
		curl_setopt($ch, CURLOPT_VERBOSE, true);
		
		
		$result = curl_exec($ch);
		echo $result;
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		curl_close($ch);
		
	}
	
}

if(!file_exists($config_file)) die("\r\nCould not find config file ".$config_file);
foreach($ips as $ip){
	$phone = new YealinkPhone($ip,$phone_user,$phone_pass);
	if($phone->success) $phone->setConfigCFG($config_file);
	
}





